# For zza

combine:
	cat SimTop.v ysyx_040510_ALU.v ysyx_040510_Arbitrating.v ysyx_040510_axi.v ysyx_040510_CLINT.v ysyx_040510_cpu.v ysyx_040510_divider.v ysyx_040510_Forwarding.v ysyx_040510_Hazard_detection.v ysyx_040510_icache.v ysyx_040510_IDU.v ysyx_040510_IFU.v ysyx_040510_MEM.v ysyx_040510_multiplier.v ysyx_040510_MuxKeyWithDefault.v ysyx_040510_NPC.v ysyx_040510_para.v ysyx_040510_PIPE_EX_MEM.v ysyx_040510_PIPE_ID_EX.v ysyx_040510_PIPE_IF_ID.v ysyx_040510_PIPE_MEM_WB.v ysyx_040510_RegisterFile.v ysyx_040510_SEXT.v > /home/zza/ysyx-workbench/ysyxSoC/ysyx/soc/ysyx_040510.v 
